[package]
name = "pokesearch"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
rustemon = { version = "3.5" }
tokio = { version = "1.41", features = ["io-std", "io-util", "rt", "rt-multi-thread"] }
toml = "0.8"
